#!/usr/bin/env node
/**
 * Delete content files that were auto-generated by `seed-from-enumeration.ts`
 * or `seed-utils.ts`'s default template. Those files are identifiable by the
 * specific shape the seeder produces:
 *
 *  services.categories is either a single { id: 'principal'|'general', ... }
 *  entry OR a list of snake_case slugs with generic descriptions.
 *
 *  testimonials has exactly 2 entries with the specific seed quotes.
 *
 *  faq has 2-3 entries matching the seeder's fixed questions.
 *
 * Curated content files (~30 hand-authored) won't match and stay.
 * Dry-run by default. Pass --apply to actually delete files.
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '../..')
const CONTENT = path.join(ROOT, 'src/content')
const APPLY = process.argv.includes('--apply')

const TEMPLATE_TESTIMONIAL_QUOTES = new Set([
  'Excelente servicio y trato profesional. Muy recomendable.',
  'Cumplieron con todo lo prometido y mas. Los volveria a elegir.',
  'Excelente servicio, los recomiendo a todos.',
  'Profesionales y confiables, una gran experiencia.',
])

const TEMPLATE_FAQ_QUESTIONS = new Set([
  '¿Como puedo contactarlos?',
  '¿Atienden en mi zona?',
  '¿Dan presupuesto sin cargo?',
])

function isTemplateShape(doc: unknown): boolean {
  const d = doc as {
    services?: { categories?: Array<{ id?: string; name?: string; description?: string }> }
    testimonials?: Array<{ quote?: string }>
    faq?: Array<{ q?: string }>
  }
  const testimonials = d.testimonials || []
  const faq = d.faq || []
  const services = d.services?.categories || []

  // Testimonials must match seed template quotes
  const testimonialsMatch =
    testimonials.length >= 1 &&
    testimonials.length <= 2 &&
    testimonials.every((t) => t.quote && TEMPLATE_TESTIMONIAL_QUOTES.has(t.quote))
  if (!testimonialsMatch) return false

  // FAQ must match seed template questions
  const faqMatch =
    faq.length >= 1 &&
    faq.length <= 3 &&
    faq.every((f) => f.q && TEMPLATE_FAQ_QUESTIONS.has(f.q))
  if (!faqMatch) return false

  // Services must be a single generic entry OR a list of seeded enum categories
  const servicesMatch =
    services.length === 1 &&
    (services[0].id === 'principal' || services[0].id === 'general') &&
    (services[0].description || '').startsWith('Servicios profesionales')
  const servicesCategoriesMatch =
    services.length > 1 &&
    services.every(
      (s) => s.description && s.description.length > 0 && (s.description.length < 120),
    )
  if (!servicesMatch && !servicesCategoriesMatch) return false

  return true
}

const files = fs.readdirSync(CONTENT).filter((f) => f.endsWith('.content.json')).sort()

let toDelete = 0
let keep = 0

for (const file of files) {
  const full = path.join(CONTENT, file)
  let doc: unknown
  try {
    doc = JSON.parse(fs.readFileSync(full, 'utf-8'))
  } catch {
    keep++
    continue
  }
  if (isTemplateShape(doc)) {
    toDelete++
    if (APPLY) fs.unlinkSync(full)
  } else {
    keep++
  }
}

console.log(`\n=== ${APPLY ? 'Pruned' : 'Would prune'} auto-seeded content ===`)
console.log(`  template-shape ${APPLY ? 'deleted' : 'removable'}: ${toDelete}`)
console.log(`  curated (kept): ${keep}`)
if (!APPLY) console.log(`\nRe-run with --apply to actually delete.`)
