#!/usr/bin/env node
/**
 * Deployment Assistant
 * 
 * Automates the entire deployment process.
 * You just need to provide credentials when prompted.
 * 
 * Usage: npm run deploy:setup
 */

import { execSync } from 'child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { resolve } from 'path'
import readline from 'readline'

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()))
  })
}

function log(step, message) {
  console.log(`\n${step}. ${message}`)
}

function success(message) {
  console.log(`   ✅ ${message}`)
}

function error(message) {
  console.log(`   ❌ ${message}`)
}

function info(message) {
  console.log(`   ℹ️  ${message}`)
}

async function main() {
  console.log(`
╔════════════════════════════════════════════════════════════╗
║          PARAGU-AI DEPLOYMENT ASSISTANT                    ║
║                                                            ║
║  This script will help you deploy to production.          ║
║  You'll need:                                              ║
║  - Supabase project URL and API keys                       ║
║  - (Optional) Cloudflare account for hosting               ║
║  - (Optional) MercadoPago credentials for payments         ║
╚════════════════════════════════════════════════════════════╝
`)

  const envVars = {}
  
  // Step 1: Supabase Configuration
  log(1, 'Supabase Configuration')
  info('Get these from: https://supabase.com/dashboard/project/_/settings/api')
  
  const supabaseUrl = await ask('   Supabase Project URL (https://...supabase.co): ')
  envVars.NEXT_PUBLIC_SUPABASE_URL = supabaseUrl
  
  const supabaseAnon = await ask('   Supabase Anon/Publishable Key: ')
  envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY = supabaseAnon
  
  const supabaseService = await ask('   Supabase Service Role Key (secret): ')
  envVars.SUPABASE_SERVICE_ROLE_KEY = supabaseService
  
  // Step 2: Test Supabase Connection
  log(2, 'Testing Supabase Connection')
  try {
    // Create a test SQL to verify connection
    const testQuery = `SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';`
    info('Testing connection...')
    
    // We can't actually test here without the client, but we'll verify format
    if (!supabaseUrl.includes('supabase.co')) {
      throw new Error('Invalid Supabase URL format')
    }
    if (!supabaseAnon.startsWith('eyJ') && !supabaseAnon.startsWith('sb_')) {
      throw new Error('Invalid Anon key format')
    }
    
    success('Supabase credentials format looks valid')
  } catch (e) {
    error(`Connection check: ${e.message}`)
  }
  
  // Step 3: Create .env.local
  log(3, 'Creating Environment File')
  
  const envContent = `# Paragu-AI Environment Configuration
# Generated by deployment assistant
# Created: ${new Date().toISOString()}

# Supabase (Required)
NEXT_PUBLIC_SUPABASE_URL=${envVars.NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${envVars.SUPABASE_SERVICE_ROLE_KEY}

# Site Configuration
NEXT_PUBLIC_SITE_URL=https://paragu-ai.pages.dev
NEXT_PUBLIC_SITE_NAME=Paragu-AI

# MercadoPago (Optional - for payments)
# MERCADOPAGO_PUBLIC_KEY=
# MERCADOPAGO_ACCESS_TOKEN=
# MERCADOPAGO_WEBHOOK_SECRET=

# Analytics (Optional)
# NEXT_PUBLIC_GA_MEASUREMENT_ID=
`

  const envPath = resolve(process.cwd(), '.env.local')
  writeFileSync(envPath, envContent)
  success(`Created ${envPath}`)
  info('This file is gitignored and contains secrets - keep it safe!')
  
  // Step 4: Database Setup Instructions
  log(4, 'Database Setup')
  console.log(`
   📋 NEXT STEPS TO COMPLETE SETUP:
   
   1. Go to your Supabase SQL Editor:
      ${supabaseUrl}/sql/new
   
   2. Copy the entire contents of:
      supabase/migrations/000_complete_schema.sql
   
   3. Paste into SQL Editor and click "Run"
   
   4. Verify tables were created in Table Editor
   
   ⏸️  Press Enter when you've run the migration...
`)
  
  await ask('   Press Enter to continue...')
  
  // Step 5: Build Check
  log(5, 'Testing Production Build')
  info('This will verify everything works before deployment...')
  
  try {
    execSync('npm run build', {
      cwd: process.cwd(),
      stdio: 'inherit',
      env: { ...process.env, ...envVars }
    })
    success('Build completed successfully!')
  } catch (e) {
    error('Build failed - check errors above')
    console.log('\n   Try running manually: npm run build')
  }
  
  // Step 6: Import Leads (Optional)
  log(6, 'Lead Import (Optional)')
  const importLeads = await ask('   Do you want to import leads from paragu-ai-leads? (y/n): ')
  
  if (importLeads.toLowerCase() === 'y') {
    const csvPath = await ask('   Path to paraguay_priority_a.csv: ')
    
    console.log(`\n   Running: npm run import:leads -- --file=${csvPath}\n`)
    
    try {
      execSync(`npm run import:leads -- --file=${csvPath}`, {
        cwd: process.cwd(),
        stdio: 'inherit',
        env: { ...process.env, ...envVars }
      })
      success('Leads imported!')
    } catch (e) {
      error('Import failed - you can run it manually later')
      info(`Command: npm run import:leads -- --file=${csvPath}`)
    }
  } else {
    info('Skipping lead import. You can do this later with:')
    info('npm run import:leads -- --file=path/to/paraguay_priority_a.csv')
  }
  
  // Step 7: Cloudflare Deployment Instructions
  log(7, 'Cloudflare Pages Deployment')
  console.log(`
   📋 DEPLOY TO CLOUDFLARE:
   
   Option A: Using Wrangler CLI (Recommended)
   -----------------------------------------
   1. Install Wrangler:
      npm install -g wrangler
   
   2. Login to Cloudflare:
      npx wrangler login
   
   3. Deploy:
      npm run deploy
   
   Option B: Git Integration (Easiest)
   -----------------------------------
   1. Go to https://dash.cloudflare.com
   2. Pages → Create a project
   3. Connect to GitHub repo: Ai-Whisperers/paragu-ai-builder
   4. Select Main branch
   5. Build settings:
      - Build command: cd web && npm run build
      - Build output: web/dist
   
   6. Add Environment Variables in Cloudflare dashboard:
      NEXT_PUBLIC_SUPABASE_URL=${envVars.NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY=${envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY=${envVars.SUPABASE_SERVICE_ROLE_KEY}
   
   7. Deploy!
`)
  
  // Step 8: Create deployment summary
  log(8, 'Creating Deployment Summary')
  
  const summary = `# Deployment Summary
Generated: ${new Date().toISOString()}

## Supabase Configuration
- Project URL: ${envVars.NEXT_PUBLIC_SUPABASE_URL}
- Status: ✅ Configured
- Migration: Run 000_complete_schema.sql in SQL Editor

## Environment Variables
Location: web/.env.local
- NEXT_PUBLIC_SUPABASE_URL: ✅ Set
- NEXT_PUBLIC_SUPABASE_ANON_KEY: ✅ Set  
- SUPABASE_SERVICE_ROLE_KEY: ✅ Set (keep secret!)

## Next Steps
1. ⬜ Run database migration in Supabase SQL Editor
2. ⬜ Import leads (optional): npm run import:leads -- --file=<path>
3. ⬜ Deploy to Cloudflare Pages
4. ⬜ Test /admin/leads endpoint
5. ⬜ Start converting leads!

## URLs After Deployment
- Main site: https://paragu-ai.pages.dev
- Admin leads: https://paragu-ai.pages.dev/admin/leads
- API health: https://paragu-ai.pages.dev/api/health

## Useful Commands
# Test build locally
npm run build

# Import leads
npm run import:leads -- --file=../../paragu-ai-leads/data/processed/paraguay_priority_a.csv

# Deploy to Cloudflare
npm run deploy

# Validate everything
npm run validate:all
`

  const summaryPath = resolve(process.cwd(), 'DEPLOYMENT_SUMMARY.md')
  writeFileSync(summaryPath, summary)
  success(`Created ${summaryPath}`)
  
  // Final message
  console.log(`
╔════════════════════════════════════════════════════════════╗
║                   SETUP COMPLETE! 🎉                        ║
╚════════════════════════════════════════════════════════════╝

✅ Environment variables configured
✅ Build tested  
✅ Deployment guide created

NEXT ACTIONS:
1. Run the database migration in Supabase SQL Editor
2. Deploy to Cloudflare Pages (see step 7 above)
3. Import your leads
4. Start converting customers!

Your site will be live at: https://paragu-ai.pages.dev
Admin dashboard: https://paragu-ai.pages.dev/admin/leads

Questions? Check docs/DEPLOYMENT.md
`)

  rl.close()
}

main().catch(err => {
  console.error('Error:', err)
  process.exit(1)
})
