#!/usr/bin/env node
/**
 * Auto-generate the section renderer mapping from the section registry.
 *
 * Scans the SECTION_CATALOG in section-registry.ts, then checks which
 * components exist as files in components/sections/. Produces a TS file
 * with imports + COMPONENTS map that the renderers can use.
 *
 * Run: tsx scripts/generate-renderer-map.ts
 * Output: lib/engine/generated/renderer-map.ts
 * Add to prebuild: "generate:renderer": "tsx scripts/generate-renderer-map.ts"
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PROJECT_ROOT = path.resolve(__dirname, '..')

const REGISTRY_PATH = path.resolve(PROJECT_ROOT, 'lib/engine/section-registry.ts')
const SECTIONS_DIR = path.resolve(PROJECT_ROOT, 'components/sections')
const OUTPUT_DIR = path.resolve(PROJECT_ROOT, 'lib/engine/generated')
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'renderer-map.ts')

// Read the section registry to extract all registered IDs
const registry = fs.readFileSync(REGISTRY_PATH, 'utf-8')

// Extract section IDs from the SECTION_CATALOG
// Pattern: "'section-id': {"
const sectionIds: string[] = []
const catalogRegex = /  '([a-z0-9-]+)':\s*\{/g
let match
while ((match = catalogRegex.exec(registry)) !== null) {
  sectionIds.push(match[1])
}

// Scan available section component files
const sectionFiles = fs.readdirSync(SECTIONS_DIR).filter((f) => f.endsWith('-section.tsx'))

// Build a map: section-id → component file info
interface ComponentInfo {
  sectionId: string
  fileName: string
  exportName: string
}

const components: ComponentInfo[] = []

for (const sid of sectionIds) {
  // The section file could be named:
  // 1. {sectionId}-section.tsx  (standard)
  // 2. {sectionId}.tsx (edge case)
  const possibleNames = [`${sid}-section.tsx`]
  const found = possibleNames.find((name) => sectionFiles.includes(name))

  if (found) {
    const filePath = path.join(SECTIONS_DIR, found)
    const content = fs.readFileSync(filePath, 'utf-8')

    // Extract the exported component name
    // Pattern: "export function XxxSection" or "export const XxxSection"
    const exportMatch = content.match(
      /export (?:function|const) ([A-Za-z0-9]+)(?:Section|[^s])/
    ) || content.match(/export (?:function|const) ([A-Za-z0-9]+)/)

    if (exportMatch) {
      components.push({
        sectionId: sid,
        fileName: found,
        exportName: exportMatch[1],
      })
    } else {
      // Try to find any React component export
      const altMatch = content.match(/export (?:function|const|class) (\w+)/)
      if (altMatch) {
        components.push({
          sectionId: sid,
          fileName: found,
          exportName: altMatch[1],
        })
      }
    }
  }
}

// Generate the TypeScript file
const lines: string[] = [
  '// Auto-generated by scripts/generate-renderer-map.ts',
  '// Regenerar con: npm run generate:renderer',
  '// DO NOT EDIT MANUALLY',
  '',
  "import type React from 'react'",
  '',
]

// Add imports
for (const c of components) {
  const importPath = `@/components/sections/${c.fileName.replace('.tsx', '')}`
  lines.push(`import { ${c.exportName} } from '${importPath}'`)
}

lines.push('')
lines.push('export const GENERATED_MAP: Record<string, React.ComponentType<any>> = {')

for (const c of components) {
  if (c.sectionId.includes('-')) {
    lines.push(`  '${c.sectionId}': ${c.exportName},`)
  } else {
    lines.push(`  ${c.sectionId}: ${c.exportName},`)
  }
}

lines.push('}')
lines.push('')

fs.mkdirSync(OUTPUT_DIR, { recursive: true })
fs.writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8')

console.log(`[generate-renderer-map] Scanned ${sectionIds.length} registered sections`)
console.log(`[generate-renderer-map] Found ${components.length} with matching component files`)
console.log(`[generate-renderer-map] Wrote ${OUTPUT_PATH}`)

// Report unmatched sections
const foundIds = new Set(components.map((c) => c.sectionId))
const missing = sectionIds.filter((id) => !foundIds.has(id))
if (missing.length > 0) {
  console.log(`[generate-renderer-map] WARNING: ${missing.length} sections have NO component file:`)
  missing.forEach((id) => console.log(`  - ${id}`))
}
