/**
 * Business Data Loader
 *
 * Abstracts the data source for business data. Currently loads from
 * demo-data.ts and optional generated lead data. Supabase integration
 * will be added once the database is configured.
 *
 * To enable Supabase (future):
 *   1. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY
 *   2. Run migrations (001_initial_schema.sql, 002_seed_demo_data.sql)
 *   3. Import leads via: npx tsx scripts/import-leads.ts
 *   4. Uncomment the Supabase section in this file
 *
 * IMPORTANT: Do NOT import @/lib/supabase/* here until Supabase is
 * configured. Even dynamic imports get traced by webpack and trigger
 * cookies() calls that break static generation on Cloudflare Pages.
 */

import type { BusinessData } from './compose'
import { getDemoBusiness, getAllDemoSlugs, DEMO_BUSINESSES } from './demo-data'

// Conditionally import lead data (generated by scripts/generate-top-leads.ts)
let LEAD_BUSINESSES: Record<string, BusinessData> = {}
try {
  // This file is auto-generated and may not exist yet
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const leadData = require('./lead-data')
  LEAD_BUSINESSES = leadData.LEAD_BUSINESSES || {}
} catch {
  // Lead data not generated yet — that's fine, will use demo data only
}

/**
 * Load a single business by slug.
 * Checks lead data first, then demo data.
 */
export async function loadBusiness(slug: string): Promise<BusinessData | null> {
  // Lead data takes priority over demo data
  if (LEAD_BUSINESSES[slug]) return LEAD_BUSINESSES[slug]

  return getDemoBusiness(slug)
}

/**
 * Load all business slugs for static generation.
 * Returns demo slugs + any lead slugs.
 */
export async function loadAllSlugs(): Promise<string[]> {
  const slugs = new Set([...getAllDemoSlugs(), ...Object.keys(LEAD_BUSINESSES)])
  return Array.from(slugs)
}

/**
 * Load all businesses (for admin dashboard).
 */
export async function loadAllBusinesses(): Promise<BusinessData[]> {
  return [
    ...Object.values(DEMO_BUSINESSES),
    ...Object.values(LEAD_BUSINESSES),
  ]
}

// ─── Supabase Integration (Uncomment when DB is configured) ────────────
//
// To enable: set real NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY,
// then uncomment the code below and update the functions above to call these.
//
// async function loadBusinessFromSupabase(slug: string): Promise<BusinessData | null> {
//   const { createClient } = await import('@/lib/supabase/server')
//   const supabase = await createClient()
//   const { data, error } = await supabase
//     .from('businesses')
//     .select('*')
//     .eq('slug', slug)
//     .eq('status', 'active')
//     .single()
//   if (error || !data) return null
//   return rowToBusinessData(data)
// }
